- hosts: jade

  roles:
    - role: traefik
      tags: traefik_deploy
      vars:
        server: "jade"

  tasks:
    - name: Deploy Glance
      import_tasks: tasks/glance.yml
      tags: glance_deploy
    - name: Deploy Servarr
      import_tasks: tasks/servarr.yml
      tags: servarr_deploy
    - name: Deploy Dozzle
      import_tasks: tasks/dozzle.yml
      tags: dozzle_deploy
    - name: Deploy Cup
      import_tasks: tasks/cup.yml
      tags: cup_deploy
    - name: Deploy Homebridge
      import_tasks: tasks/homebridge.yml
      tags: homebridge_deploy
    - name: Deploy PiHole
      import_tasks: tasks/pihole.yml
      tags: pihole_deploy
    - name: Deploy PocketID
      import_tasks: tasks/pocketid.yml
      tags: pocketid_deploy
    - name: Deploy Ntfy
      import_tasks: tasks/ntfy.yml
      tags: ntfy_deploy
    - name: Deploy NZBGet
      import_tasks: tasks/nzbget.yml
      tags: nzbget_deploy
    - name: Deploy Tautulli
      import_tasks: tasks/tautulli.yml
      tags: tautulli_deploy
    - name: Deploy Tinyauth
      import_tasks: tasks/tinyauth.yml
      tags: tinyauth_deploy
    - name: Deploy Code Server
      import_tasks: tasks/codeserver.yml
      tags: codeserver_deploy
    - name: Deploy Dashdot
      import_tasks: tasks/dashdot.yml
      tags: dashdot_deploy
    - name: Deploy Romm
      import_tasks: tasks/romm.yml
      tags: romm_deploy
    - name: Deploy Owncloud
      import_tasks: tasks/owncloud.yml
      tags: owncloud_deploy
    - name: Deploy Excalidraw
      import_tasks: tasks/excalidraw.yml
      tags: excalidraw_deploy
    - name: Deploy Vaultwarden
      import_tasks: tasks/vaultwarden.yml
      tags: vaultwarden_deploy
    - name: Deploy Immich
      import_tasks: tasks/immich.yml
      tags: immich_deploy
    - name: Deploy Navidrome
      import_tasks: tasks/navidrome.yml
      tags: navidrome_deploy
    - name: Deploy Drop
      import_tasks: tasks/drop.yml
      tags: drop_deploy
    - name: Deploy Home Assistant
      import_tasks: tasks/home-assistant.yml
      tags: home-assistant_deploy
    - name: Deploy Gluetun
      import_tasks: tasks/gluetun.yml
      tags: gluetun_deploy
    - name: Deploy QBittorrent
      import_tasks: tasks/qbittorrent.yml
      tags: qbittorrent_deploy
    - name: Deploy Jackett
      import_tasks: tasks/jackett.yml
      tags: jackett_deploy
    - name: Deploy NFL Proxy
      import_tasks: tasks/nfl-proxy.yml
      tags: nfl-proxy_deploy
    - name: Deploy Uptime Kuma
      import_tasks: tasks/uptime-kuma.yml
      tags: uptime-kuma_deploy
    - name: Deploy CouchDB for obsidian
      import_tasks: tasks/obsidian.yml
      tags: obsidian_deploy

- hosts: jackson

  roles:
    - role: traefik
      tags: traefik_deploy
    - role: fivem
      tags: fivem_deploy

  tasks:
    - name: Deploy Gitea
      import_tasks: tasks/gitea.yml
      tags: gitea_deploy
    - name: Deploy API
      import_tasks: tasks/api.yml
      tags: api_deploy
    - name: Deploy Storage API
      import_tasks: tasks/storage-api.yml
      tags: storage-api_deploy
    - name: Deploy Plausible
      import_tasks: tasks/plausible.yml
      tags: plausible_deploy
    - name: Deploy Owncloud
      import_tasks: tasks/owncloud.yml
      tags: owncloud_deploy

- hosts: nas

  tasks:
    - name: Deploy Plex
      import_tasks: tasks/plex.yml
      tags: plex_deploy
    - name: Deploy Frigate
      import_tasks: tasks/frigate.yml
      tags: frigate_deploy
