- hosts: jade

  roles:
    - role: caddy
      tags: caddy_deploy
    - role: gitea-runner
      tags: gitea-runner_deploy

  tasks:
    - name: Deploy Glance
      import_tasks: tasks/glance.yml
      tags: glance_deploy
    - name: Deploy Servarr
      import_tasks: tasks/servarr.yml
      tags: servarr_deploy
    - name: Deploy Dozzle
      import_tasks: tasks/dozzle.yml
      tags: dozzle_deploy
    - name: Deploy Cup
      import_tasks: tasks/cup.yml
      tags: cup_deploy
    - name: Deploy Homebridge
      import_tasks: tasks/homebridge.yml
      tags: homebridge_deploy
    - name: Deploy PiHole
      import_tasks: tasks/pihole.yml
      tags: pihole_deploy
    - name: Deploy PocketID
      import_tasks: tasks/pocketid.yml
      tags: pocketid_deploy
    - name: Deploy Ntfy
      import_tasks: tasks/ntfy.yml
      tags: ntfy_deploy
    - name: Deploy NZBGet
      import_tasks: tasks/nzbget.yml
      tags: nzbget_deploy
    - name: Deploy Tautulli
      import_tasks: tasks/tautulli.yml
      tags: tautulli_deploy
    - name: Deploy Tinyauth
      import_tasks: tasks/tinyauth.yml
      tags: tinyauth_deploy
    - name: Deploy Code Server
      import_tasks: tasks/codeserver.yml
      tags: codeserver_deploy
    - name: Deploy Dashdot
      import_tasks: tasks/dashdot.yml
      tags: dashdot_deploy
    - name: Deploy Romm
      import_tasks: tasks/romm.yml
      tags: romm_deploy
    - name: Deploy Nextcloud
      import_tasks: tasks/nextcloud.yml
      tags: nextcloud_deploy
    - name: Deploy Excalidraw
      import_tasks: tasks/excalidraw.yml
      tags: excalidraw_deploy
    - name: Deploy Vaultwarden
      import_tasks: tasks/vaultwarden.yml
      tags: vaultwarden_deploy
    - name: Deploy Immich
      import_tasks: tasks/immich.yml
      tags: immich_deploy
    - name: Deploy Jellyfin
      import_tasks: tasks/jellyfin.yml
      tags: jellyfin_deploy
    - name: Deploy Navidrome
      import_tasks: tasks/navidrome.yml
      tags: navidrome_deploy
    - name: Deploy Monitoring Stack
      import_tasks: tasks/monitoring.yml
      tags: monitoring_deploy

- hosts: jackson

  roles:
    - role: caddy
      tags: caddy_deploy

  tasks:
    - name: Deploy Gitea
      import_tasks: tasks/gitea.yml
      tags: gitea_deploy
    - name: Deploy API
      import_tasks: tasks/api.yml
      tags: api_deploy
    - name: Deploy Storage API
      import_tasks: tasks/storage-api.yml
      tags: storage-api_deploy
    - name: Deploy Plausible
      import_tasks: tasks/plausible.yml
      tags: plausible_deploy
    - name: Deploy Nextcloud
      import_tasks: tasks/nextcloud.yml
      tags: nextcloud_deploy
