name: Deploy All Containers

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Prepare
    runs-on: runner
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add <(echo "${{ secrets.SSH_KEY }}")
          echo "HOST *" > ~/.ssh/config
          echo "${{ secrets.VAULT_PASS }}" > ~/.vault_pass.txt
          chmod 600 ansible.cfg 
          /usr/bin/ansible-playbook main.yml --vault-password-file ~/.vault_pass.txt
